### ISSUE TITLE
nbdkit server crashes with "munmap_chunk(): invalid pointer" when nbdcopy starts

### ISSUE THREAD

**Issue by paulfelton** [vexxhost/migratekit#14]
Hi,

I'm trying to migrate an Oracle Linux 8 VM from VMware to Openstack.  From what I can see it's successfully creating the snapshot, as I can see that in the vSphere portal.  It starts the `nbdkit` server successfully, and I can see the pid for the server and the socket within `/tmp`.  It correctly identifies that this is a first-time copy and a full copy is needed.  

But when it comes to launch `nbdcopy`, the server appears to crash, with an invalid pointer error.

This is the command we run, slightly redacted.  We have mirrored the docker image to our own harbor for simplicity.
`docker run -it --rm --privileged -v /etc/hosts:/etc/hosts:ro -v /dev:/dev  -v /usr/lib64/vmware-vix-disklib/:/usr/lib64/vmware-vix-disklib:ro --env-file <(env | grep OS_) migratekit:latest  migrate --vmware-endpoint REDACTED_ENDPOINT  --vmware-username REDACTED --vmware-password REDACTED --vmware-path "/datacentre/vm/REDACTED"`

I'm running on Oracle Linux 9.4, Docker 27.2.0.  Our VDDK from VMware is 8.0.3. 

I've seen that you've suggested on #9 to use Docker on Ubuntu.  We switched from Podman to Docker but that didn't help.  I don't think I can move from OEL9 to Ubuntu as I'm restricted as to what I can use.

I've tried modifying the golang code to turn on verbose debug, and add additional logging.  Right before the `invalid pointer` error, I see two warnings...I'm not sure if they are related or not.

Here's the output of nbdkit/vddk immediately after the nbdcopy begins.

```
Running command: /usr/bin/nbdcopy --progress=3 nbd+unix:///?socket=/tmp/migratekit-3504199861/nbdkit.sock /dev/vdd --destination-is-zero  destination=/dev/vdd source="nbd+unix:///?socket=/tmp/migratekit-3504199861/nbdkit.sock"
nbdkit: debug: accepted connection
nbdkit: vddk[1]: debug: vddk: preconnect
nbdkit: vddk[1]: debug: newstyle negotiation: flags: global 0x3
nbdkit: vddk[1]: debug: newstyle negotiation: client flags: 0x3
nbdkit: vddk[1]: debug: replying to unknown (0xb) with unknown (0x80000001)
nbdkit: vddk[1]: debug: newstyle negotiation: unknown (0x8): client requested structured replies
nbdkit: vddk[1]: debug: replying to unknown (0x8) with unknown (0x1)
nbdkit: vddk[1]: debug: newstyle negotiation: unknown (0xa): client requested export ''
nbdkit: vddk[1]: debug: newstyle negotiation: unknown (0xa): set count: 1
nbdkit: vddk[1]: debug: newstyle negotiation: unknown (0xa): set base:allocation
nbdkit: vddk[1]: debug: newstyle negotiation: unknown (0xa): replying with base:allocation id 1
nbdkit: vddk[1]: debug: replying to unknown (0xa) with unknown (0x1)
nbdkit: vddk[1]: debug: newstyle negotiation: unknown (0xa): reply complete
nbdkit: vddk[1]: debug: newstyle negotiation: unknown (0x7): client requested export ''
nbdkit: vddk[1]: debug: vddk: open readonly=1 exportname="" tls=0
nbdkit: vddk[1]: debug: vddk: default_export readonly=1 tls=0
nbdkit: vddk[1]: debug: VDDK call: VixDiskLib_AllocateConnectParams ()
nbdkit: vddk[1]: debug: VDDK call: VixDiskLib_ConnectEx (h->params, 1, snapshot-76330, NULL, &connection)
nbdkit: vddk[1]: debug: VixDiskLib: VixDiskLib_ConnectEx: Establish connection using (null).
nbdkit: vddk[1]: debug: VixDiskLib: VixDiskLibConnectInt: Establish connection.
nbdkit: vddk[1]: debug: VixDiskLib: Resolve host.
nbdkit: vddk[1]: debug: VDDK call: VixDiskLib_Open (connection, [REDACTED] REDACTED/REDACTED.vmdk, 68, &handle)
nbdkit: vddk[1]: debug: VixDiskLib: VixDiskLib_OpenEx: Open disk '[REDACTED] REDACTED/REDACTED.vmdk'.
nbdkit: vddk[1]: debug: 2024-09-03T11:33:50.865Z warning -[00078] [Originator@6876 sub=DiskEnum] ScanSysfsDir: File path /sys/class/nvme not exist for nvme.
nbdkit: vddk[1]: debug: 2024-09-03T11:33:50.865Z warning -[00078] [Originator@6876 sub=DiskEnum] ScanSysfsDir: File path /sys/class/nvme-subsystem not exist for nvme.
munmap_chunk(): invalid pointer
nbdcopy: nbd+unix:///?socket=/tmp/migratekit-3504199861/nbdkit.sock: nbd_connect_uri: recv: server disconnected unexpectedly
```

Do you have any suggestions on where to go from here?  Myself and a colleague are comfortable modifying the golang code to provide any additional debug information that might be helpful.  But we are more reluctant to dive into the `c` code behind `nbdkit`. :-)

**Comment by mnaser** [comment]
I've ran into this error a few times and it feels like it's an nbdkit issue.  I just pushed up #15 to get more debug logging out of virt-v2v but we can totally re-use that infrastructure for other components like `nbdkit`.

What flags did you add to get debug out of nbdkit?  I can add that to the `--debug`.

**Comment by mnaser** [comment]
FTR: https://gitlab.com/nbdkit/nbdkit/-/issues/24

**Comment by mnaser** [comment]
@paulfelton can you try running your commands with `-v /sys:/sys` -- It may be the lack of a proper `/sys` mount inside the Docker container.

**Comment by mnaser** [comment]
https://github.com/vexxhost/migratekit/pull/16

Once we land this, I think this will solve your issue.

**Comment by mnaser** [comment]
@paulfelton can you please try pulling down the latest image and see if it works now? :)

**Comment by paulfelton** [comment]
@mnaser Thanks for this.  I've retested and I'm no longer getting the invalid pointer.  I'm now getting connectivity problems to the esxhost:

```nbdkit: vddk[1]: error: [NFC ERROR]NfcNewAuthdConnectionEx: Failed to connect: Error reading from vmware-authd socket. Reason: Resource temporarily unavailable
nbdkit: vddk[1]: error: [NFC ERROR]NfcNewAuthdConnectionEx: Failed to connect to peer. Error: Error reading from vmware-authd socket. Reason: Resource temporarily unavailable
nbdkit: vddk[1]: error: [NFC ERROR]NfcEstablishAuthCnxToServer: Failed to create new AuthD connection: Error reading from vmware-authd socket. Reason: Resource temporarily unavailable
nbdkit: vddk[1]: error: [NFC ERROR]Nfc_BindAndEstablishAuthdCnx3: Failed to create a connection with server

**Comment by mnaser** [comment]
@paulfelton https://www.veritas.com/support/en_US/article.100053291 is probably the same issue, I suggest having a look there.  The debug flag for nbdkit might include helpful info.

**Comment by paulfelton** [comment]
Yes, I think that's right.

We've moved beyond this now, and are failing later in virt-v2v, so I think we can close this issue - thanks for your help.
