### ISSUE TITLE
Problems with migrating some operating systems

### ISSUE THREAD

**Issue by FlorianBoegl** [vexxhost/migratekit#18]
Hello,

my team and I are currently migrating our servers to openstack, and we migrated some of our virtual machines with the migratekit correct and it works totally fine ( Ubuntu ).
But we got some problems with migrating some virtual machines, specifically virtual machines with the operating systems  Windows and openSUSE.
We see the created Volume and can launch an instance in openstack.
Both instances for Windows and openSUSE also have a functioning/running Console.
The problem is all Windows machines never get past the "Windows recovery mode".
And for openSUSE its the "same" problem.
We think the problem is that the virtual machines in openstack don't recognize their volumes correctly.

To migrate we used the command:

docker run -it --rm --privileged \
  --network host \
  -v /dev:/dev \
  -v /usr/lib64/vmware-vix-disklib/:/usr/lib64/vmware-vix-disklib:ro \
  --env-file <(env | grep OS_) \
  registry.atmosphere.dev/library/migratekit:latest \
  migrate \
  --vmware-endpoint vmware.local \
  --vmware-username username \
  --vmware-password password \
  --vmware-path /ha-datacenter/vm/migration-test

I also tried the flag --disk-bus-type with scsi and virtio.

Thanks for your time and any help is appreciated. :)

**Comment by mnaser** [comment]
Do these systems have more than 1 boot volume by any chance?

**Comment by FlorianBoegl** [comment]
The windows machine has two bootable volumes, but only one volume has windows on it. 
I tried the migration command with flavor and network mapping and the logs were very interesting.
Both volumes had logs saying: 
INFO[0008] Volume created, setting to bootable           volume_id=...

Part of the logs from second volume:
...
Incremental copy 100% [=============================================================================] (300/300 GiB, 1.7 TiB/s)[0s:16s]

INFO[1973] Running virt-v2v-in-place
[   0.0] Setting up the source: -i disk /dev/sdb
[   1.2] Opening the source
[  11.6] Inspecting the source
virt-v2v-in-place: error: inspection could not detect the source guest (or
physical machine).

Assuming that you are running virt-v2v/virt-p2v on a source which is
supported (and not, for example, a blank disk), then this should not
happen.

No root device found in this operating system image.
If reporting bugs, run virt-v2v-in-place with debugging enabled and include

the complete output:
  virt-v2v-in-place -v -x [...]
...


--------------------------------------------------------------------------------------
Migratekit stopped here, but it created two volumes in openstack.

The good thing is that I launched an Instance from the first volume, and it seems to work correct.
Will test this more in the next couple of days, and if machines with only one volume just migrate correct with the network mapping and flavor.

**Comment by FlorianBoegl** [comment]
Just migrated openSUSE ( with one  volume ) with the network mapping and flavor command. Seems to do the trick, created an Instance that looks fine... :)

**Comment by mnaser** [comment]
@FlorianBoegl that windows issue is probably a bug we've fixed where you have multiple volumes.  Make sure to pull the last image and it should work just fine!  Please try again :)

**Comment by paulfelton** [comment]
Interestingly, that latest #19 commit helped me progress with a linux vm that was failing (OEL9) with the same error.

**Comment by mnaser** [comment]
Cool!  Let me know if you want me to keep this issue open. :)

**Comment by FlorianBoegl** [comment]
@mnaser , No I think it's good. Thanks again ;)
