### ISSUE TITLE
After cutover with error, we need to start the full copy data again. Could the migratekit do the incremental copy after the failed cutover? 

### ISSUE THREAD

**Issue by Apiwat-p** [vexxhost/migratekit#22]
Dear Mohammed Naser,

              We use the MigrateKit and very happy with it. But when we try to cutover and the Error occurred, we need to start the full copy data again. In the case that the data storage more than 1 TB, it take time too much.

              Cloud the MigrateKit did solved this issue?

Thank you,
Apiwat P.

**Comment by mnaser** [comment]
Unfortunately, if it fails during the `virt-v2v` stage, we're not able to reliably do a migration cycle that is differential based because the blocks were modified by `virt-v2v`.

What kind of issues are you running into, perhaps we can just fix those errors instead?

**Comment by Apiwat-p** [comment]
Dear Mohammed Naser,

                  Thank you for your answer.

                  There is error about the insufficient memory. We need to start the full copy again and can cutover success properly. 

                  The Migrate Server had been restart then the logs gone. Sorry about this if we found the logs of this problem again we will show the logs.
                  
  Best Regards,
  Apiwat P.

**Comment by mnaser** [comment]
Indeed, please open up a new ticket with the logs of the migration the next time around. :)
