### ISSUE TITLE
Is it possible to specify network-id and let openstack choose the IP from dhcp pool?

### ISSUE THREAD

**Issue by taboche** [vexxhost/migratekit#27]

**Comment by mnaser** [comment]
Yes.  You can simply just omit the IP address and it will pick an IP address from the pool.

**Comment by taboche** [comment]
Thanks for the quick reply. Can the MAC assignment be optional instead of required?

**Comment by mnaser** [comment]
No, because that's the only way we map the NIC from the old MVware system to the new one :)
