### ISSUE TITLE
Error reading

### ISSUE THREAD

**Issue by cohl790** [vexxhost/migratekit#4]
Currently testing the tool but getting always the failure "ERRO[0028] Error reading progress: read |0: file already closed" independent of the source. Is there any way to get more log information ?

**Comment by mnaser** [comment]
@cohl790 Can you try the latest image?  The latest images actually ship a full output of the command so would be useful if you can share that.

**Comment by cohl790** [comment]
Great, thanks I can now see that it’s a blocked session on port 902 to the corresponding ESX server

 

 

Von: Mohammed Naser ***@***.***>
Antworten an: vexxhost/migratekit ***@***.***>
Datum: Dienstag, 9. Juli 2024 um 02:39
An: vexxhost/migratekit ***@***.***>
Cc: "Ohliger, Christoph" ***@***.***>, Mention ***@***.***>
Betreff: Re: [vexxhost/migratekit] Error reading (Issue #4)

 

@cohl790 Can you try the latest image? The latest images actually ship a full output of the command so would be useful if you can share that.

**Comment by mnaser** [comment]
Awesome.  Did it get unblocked afterwards?

**Comment by cohl790** [comment]
I am on the way and will update this thread

 

Von: Mohammed Naser ***@***.***>
Antworten an: vexxhost/migratekit ***@***.***>
Datum: Dienstag, 9. Juli 2024 um 17:33
An: vexxhost/migratekit ***@***.***>
Cc: "Ohliger, Christoph" ***@***.***>, Mention ***@***.***>
Betreff: Re: [vexxhost/migratekit] Error reading (Issue #4)

 

Awesome. Did it get unblocked afterwards?

**Comment by cohl790** [comment]
Great tool ! it works

 

Von: Mohammed Naser ***@***.***>
Antworten an: vexxhost/migratekit ***@***.***>
Datum: Dienstag, 9. Juli 2024 um 17:33
An: vexxhost/migratekit ***@***.***>
Cc: "Ohliger, Christoph" ***@***.***>, Mention ***@***.***>
Betreff: Re: [vexxhost/migratekit] Error reading (Issue #4)

 

Awesome. Did it get unblocked afterwards?

**Comment by mnaser** [comment]
Awesome, so happy to hear.  I've closed it.  :)
