### ISSUE TITLE
Device not found

### ISSUE THREAD

**Issue by vsford** [vexxhost/migratekit#42]
I am getting an intermittent error. During the run the volume says attaching and then when it fails, it shows attached.

Running on 22.04.5 LTS - on openstack, geneve network with a floating "internal" VLAN IP

docker --version
Docker version 24.0.7, build 24.0.7-0ubuntu2~22.04.1
registry.atmosphere.dev/library/migratekit   latest     129611dd3058   2 days ago     2.39GB

Debug log

> INFO[0000] Setting Disk Bus: virtio                     
Creating snapshot 100% [================================================================================================================================================================================================================================] (100/100) [0s:0s]
DEBU[0000] Running command: /usr/sbin/nbdkit --exit-with-parent --readonly --foreground --unix=/tmp/migratekit-3967406212/nbdkit.sock --pidfile=/tmp/migratekit-3967406212/nbdkit.pid vddk server=<redacted> user=<redacted>password=<redacted> thumbprint=EC:79:2E:E1:4B:2A:50:28:2B:52:C3:F4:8E:B4:86:D7:CD:C6:E5:6B compression=skipz vm=moref=vm-58870 snapshot=snapshot-114415 transports=file:nbdssl:nbd [<redacted>] duo/duo.vmdk 
INFO[0002] Starting incremental copy                    
INFO[0002] Attaching volume                              volume_id=dbdc1acf-a0d3-4e27-adb2-d52767e07bb9
INFO[0003] Detected instance UUID, attaching volume...   instance_uuid=322c5d6e-03d6-45d0-8df7-1888b302a0f7
INFO[0005] Device for volume not found, checking again...  volume_id=dbdc1acf-a0d3-4e27-adb2-d52767e07bb9
INFO[0006] Device for volume not found, checking again...  volume_id=dbdc1acf-a0d3-4e27-adb2-d52767e07bb9
INFO[0007] Device for volume not found, checking again...  volume_id=dbdc1acf-a0d3-4e27-adb2-d52767e07bb9
INFO[0008] Device for volume not found, checking again...  volume_id=dbdc1acf-a0d3-4e27-adb2-d52767e07bb9
INFO[0009] Device for volume not found, checking again...  volume_id=dbdc1acf-a0d3-4e27-adb2-d52767e07bb9
INFO[0010] Device for volume not found, checking again...  volume_id=dbdc1acf-a0d3-4e27-adb2-d52767e07bb9
INFO[0011] Device for volume not found, checking again...  volume_id=dbdc1acf-a0d3-4e27-adb2-d52767e07bb9
INFO[0012] Device for volume not found, checking again...  volume_id=dbdc1acf-a0d3-4e27-adb2-d52767e07bb9
INFO[0013] Device for volume not found, checking again...  volume_id=dbdc1acf-a0d3-4e27-adb2-d52767e07bb9
INFO[0014] Device for volume not found, checking again...  volume_id=dbdc1acf-a0d3-4e27-adb2-d52767e07bb9
INFO[0015] Device for volume not found, checking again...  volume_id=dbdc1acf-a0d3-4e27-adb2-d52767e07bb9
INFO[0016] Device for volume not found, checking again...  volume_id=dbdc1acf-a0d3-4e27-adb2-d52767e07bb9
INFO[0017] Device for volume not found, checking again...  volume_id=dbdc1acf-a0d3-4e27-adb2-d52767e07bb9
INFO[0018] Device for volume not found, checking again...  volume_id=dbdc1acf-a0d3-4e27-adb2-d52767e07bb9
INFO[0019] Device for volume not found, checking again...  volume_id=dbdc1acf-a0d3-4e27-adb2-d52767e07bb9
INFO[0020] Device for volume not found, checking again...  volume_id=dbdc1acf-a0d3-4e27-adb2-d52767e07bb9
INFO[0021] Device for volume not found, checking again...  volume_id=dbdc1acf-a0d3-4e27-adb2-d52767e07bb9
INFO[0022] Device for volume not found, checking again...  volume_id=dbdc1acf-a0d3-4e27-adb2-d52767e07bb9
INFO[0023] Device for volume not found, checking again...  volume_id=dbdc1acf-a0d3-4e27-adb2-d52767e07bb9
INFO[0024] Device for volume not found, checking again...  volume_id=dbdc1acf-a0d3-4e27-adb2-d52767e07bb9
INFO[0025] Device for volume not found, checking again...  volume_id=dbdc1acf-a0d3-4e27-adb2-d52767e07bb9
INFO[0026] Device for volume not found, checking again...  volume_id=dbdc1acf-a0d3-4e27-adb2-d52767e07bb9
INFO[0027] Device for volume not found, checking again...  volume_id=dbdc1acf-a0d3-4e27-adb2-d52767e07bb9
INFO[0028] Device for volume not found, checking again...  volume_id=dbdc1acf-a0d3-4e27-adb2-d52767e07bb9
INFO[0029] Device for volume not found, checking again...  volume_id=dbdc1acf-a0d3-4e27-adb2-d52767e07bb9
INFO[0030] Device for volume not found, checking again...  volume_id=dbdc1acf-a0d3-4e27-adb2-d52767e07bb9
INFO[0031] Device for volume not found, checking again...  volume_id=dbdc1acf-a0d3-4e27-adb2-d52767e07bb9
INFO[0032] Device for volume not found, checking again...  volume_id=dbdc1acf-a0d3-4e27-adb2-d52767e07bb9
INFO[0033] Device for volume not found, checking again...  volume_id=dbdc1acf-a0d3-4e27-adb2-d52767e07bb9
INFO[0034] Device for volume not found, checking again...  volume_id=dbdc1acf-a0d3-4e27-adb2-d52767e07bb9
INFO[0035] Device for volume not found, checking again...  volume_id=dbdc1acf-a0d3-4e27-adb2-d52767e07bb9
INFO[0036] Device for volume not found, checking again...  volume_id=dbdc1acf-a0d3-4e27-adb2-d52767e07bb9
INFO[0037] Device for volume not found, checking again...  volume_id=dbdc1acf-a0d3-4e27-adb2-d52767e07bb9
INFO[0038] Device for volume not found, checking again...  volume_id=dbdc1acf-a0d3-4e27-adb2-d52767e07bb9
INFO[0039] Device for volume not found, checking again...  volume_id=dbdc1acf-a0d3-4e27-adb2-d52767e07bb9
INFO[0040] Device for volume not found, checking again...  volume_id=dbdc1acf-a0d3-4e27-adb2-d52767e07bb9
INFO[0041] Device for volume not found, checking again...  volume_id=dbdc1acf-a0d3-4e27-adb2-d52767e07bb9
INFO[0042] Device for volume not found, checking again...  volume_id=dbdc1acf-a0d3-4e27-adb2-d52767e07bb9
INFO[0043] Device for volume not found, checking again...  volume_id=dbdc1acf-a0d3-4e27-adb2-d52767e07bb9
INFO[0044] Device for volume not found, checking again...  volume_id=dbdc1acf-a0d3-4e27-adb2-d52767e07bb9
INFO[0121] Device for volume not found, checking again...  volume_id=dbdc1acf-a0d3-4e27-adb2-d52767e07bb9
INFO[0122] Device for volume not found, checking again...  volume_id=dbdc1acf-a0d3-4e27-adb2-d52767e07bb9
INFO[0123] Device for volume not found, checking again...  volume_id=dbdc1acf-a0d3-4e27-adb2-d52767e07bb9
Removing snapshot 100% [================================================================================================================================================================================================================================] (100/100)[1s:47s]
Error: timed out waiting for volume to attach
Usage:
  migratekit migrate [flags]

**Comment by mnaser** [comment]
Is it possible that volumes take a long time to attach in your environment?  I wonder if we should increase the timeout for that to handle those cases.

**Comment by vsford** [comment]
It is taking a long time for the volumes to mount that I am looking to see if there is more of an issue with that.

If selecting a timeout was a variable to set it could possibly work, allowing users to select the amount of time applicable to the environment.
