### ISSUE TITLE
Is it possible to not shut down source VM after cutover command?

### ISSUE THREAD

**Issue by FlorianBoegl** [vexxhost/migratekit#49]
Hello, is there a way to not shut down the source VM I migrated to cloud at the end of cutover command?

I see this message.
INFO[0339] Completed migration cycle, shutting down source VM

Thanks for the help! :)

**Comment by mnaser** [comment]
@FlorianBoegl you will need to add this feature yourself or engage our team to request it, however, I wonder what the use case here.

**Comment by FlorianBoegl** [comment]
@mnaser sry for late response, usecase ist that we first want to test the migrated VM before its online.
We have issues sometimes after migrating the VM that are not caused by migratekit, its related to our Cloud Provider...
I will close this issue since it would be only a nice to have thing ;)
