### ISSUE TITLE
Change Block Tracking problem

### ISSUE THREAD

**Issue by morten-gh** [vexxhost/migratekit#50]
When running migratekit I'm getting "Error: CBT is not enabled on disk 2000" even though I have enabled it on the vm to migrate. I've tried to configure ctkEnabled:true for the entire vm but also scsi0:0.ctkEnabled: true, same error message. Any idea what the problem might be?

Thanks in advance!

**Comment by mnaser** [comment]
@morten-gh is it possible you haven't restarted your VM yet cause I think that's needed to enable CBT.

**Comment by michael-salo** [comment]
@morten-gh  You need to enable CBT not just per VM and for each disk attached to a VM and reboot a VM after

**Comment by michael-salo** [comment]
@morten-gh, yes. VM should be running on Openstack.
