### ISSUE TITLE
Error  tls failed to verify certificate x509 certificate signed by unknown authority

### ISSUE THREAD

**Issue by jpvargasit911** [vexxhost/migratekit#51]
I get this error when MigrateKit is trying to authenticate to Openstack 2023.2
Error: Get "https://api.in-a-box.cloud:5000/": tls: failed to verify certificate: x509: certificate signed by unknown authority

**Comment by jpvargasit911** [comment]
how can we force migratekit to accept the self-signed  certificate?

**Comment by jpvargasit911** [comment]
Reading the code I found an environment var to tell migratekit to ignore self signed certificates OS_INSECURE
This variable fixes the issue.

**Comment by mnaser** [comment]
Glad you found it, that's why open source is awesome. :)
