### ISSUE TITLE
Not working on ESXi 7.0 (U1) Free License

### ISSUE THREAD

**Issue by Belgeron** [vexxhost/migratekit#7]
We tried to migrate our old ESXi Standalone infrastucture with this tool.
At the readme is not stated which services, versions or licenses are required that the migration is working. Could you bring some clarification to this, would be nice.

When we try it, we always getting:
`Error: ServerFaultCode: Current license or ESXi version prohibits execution of the requested operation.`

We tried to migrate our old ESXi Standalone infrastucture with this tool.

**Comment by fnpanic** [comment]
From my point of view the API of the ESXi free is restricted and so it think this is the reason why it is not working.

**Comment by mnaser** [comment]
I added a note on this in the README file.

https://github.com/vexxhost/migratekit/commit/786fa3f6e549cf40e6f08d39a609c6169c3a95a5
